name: Check-on-push

# Run this workflow every time a new commit pushed to your repository
on: 
  push:
    branches: 
      - master
      - dev
  pull_request:
    branches: 
      - master
      - dev

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  Run-linter-and-tests:
    # Name the Job
    name: Lint n test
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node and npm
        uses: actions/setup-node@v1
        with:
          node-version: 13.12.0
      - name: install packages
        run: npm install .
      # Runs the Linter action
      - name: Run Linter
        run: npm run lint
      # Run testcases
      - name: Run tests
        run: npm run test-on-github
        
