name: Check-on-push

# Run this workflow every time a new commit pushed to your repository
on: 
  push:
  pull_request:
    branches: 
      - master
      - dev

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  Run-Grammar-tests:
    # Name the Job
    name: Run Grammar tests
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node and npm
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Run tests
        run: |
          cd tree-sitter-usfm3
          npm install .
          ./node_modules/.bin/tree-sitter generate
          ./node_modules/.bin/tree-sitter test

  Run-Python-tests:
    name: Run Python tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.10.6'
            - name: Create Virtual Environment
        run: python -m venv ENV-dev

      - name: Use VENV
        run: source ENV-dev/bin/activate

      - name: install packages
        working-directory: ./python-usfm-parser
        run: pip install -r dev-requirements.txt

      - name: Run linter
        working-directory: ./python-usfm-parser
        run: pytest tests/test_parsing_errors

