# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  Test-grammar:
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node and npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run tests
        run: |
          cd tree-sitter-usfm3
          npm install --save nan
          npm install --save-dev tree-sitter-cli
          ./node_modules/.bin/tree-sitter generate
          ./node_modules/.bin/tree-sitter test

  Publish-grammar:
    needs: Test-grammar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20.4
          registry-url: https://registry.npmjs.org/
      - run: |
          cd tree-sitter-usfm3
          npm install --save nan
          npm install --save-dev tree-sitter-cli
          ./node_modules/.bin/tree-sitter generate
          npm publish .
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  Publish-node-usfm-grammar:
    needs: Test-grammar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20.4
          registry-url: https://registry.npmjs.org/
      - run: |
          cd node-usfm-parser
          sed -i '/"tree-sitter-usfm3":.*/d' package.json
          npm install .
          git checkout -- package.json
          npm run build
          npm publish . 
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  Publish-web-usfm-grammar:
    needs: Test-grammar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20.4
          registry-url: https://registry.npmjs.org/
      - name: Build Grammar
        run: |
          cd tree-sitter-usfm3
          npm install --save nan
          npm install --save-dev tree-sitter-cli
          ./node_modules/.bin/tree-sitter generate
          ./node_modules/.bin/tree-sitter build --wasm
          cp tree-sitter-usfm3.wasm ../web-usfm-parser/tree-sitter-usfm.wasm
      - name: Install dependencies
        run: |
          cd web-usfm-parser/
          npm install .
          cp ./node_modules/web-tree-sitter/tree-sitter.js src/web-tree-sitter/
          cp ./node_modules/web-tree-sitter/tree-sitter.wasm ./
      - name: Build and publish
        run: |
          cd web-usfm-parser/
          npm run build
          npm publish .
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
