name: PyPI Publish

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
        # os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3
      - name: Setup node and npm
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build the tree-sitter parser
        run: |
          cd tree-sitter-usfm3
          npm install .
          ./node_modules/.bin/tree-sitter generate

      # - name: Build wheels
      #   uses: pypa/cibuildwheel@v2.9.0
      
      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.9.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # CIBW_BUILD_FRONTEND: "build"  #python -m build instead of python -m pip wheel
          CIBW_ARCHS_LINUX: "x86_64 i686"
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_BUILD: >
              python3.10 -m pip install tree-sitter==0.20.0 &&
              python3.10 python-usfm-parser/src/grammar_rebuild.py tree-sitter-usfm3 python-usfm-parser/src/usfm_grammar/my-languages.so
        with:
          package-dir: python-usfm-parser
          output-dir: python-usfm-parser/wheelhouse
          config-file: "python-usfm-parser/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: python-usfm-parser/wheelhouse/*.whl