name: PyPI Publish

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.9.0
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        with:
          package-dir: python-usfm-parser
          output-dir: python-usfm-parser/wheelhouse
          config-file: "python-usfm-parser/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: python-usfm-parser/wheelhouse/*.whl