name: PyPI Publish

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
        # os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.9.0
        env:
          CIBW_BUILD_FRONTEND: "build"  #python -m build instead of python -m pip wheel
          CIBW_ARCHS_LINUX: "x86_64 i686"
          CIBW_BEFORE_BUILD: python3.10 python-usfm-parser/src/grammar_rebuild.py tree-sitter-usfm3 python-usfm-parser/src/usfm_grammar/my-languages.so
        with:
          package-dir: python-usfm-parser
          output-dir: python-usfm-parser/wheelhouse
          config-file: "python-usfm-parser/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: python-usfm-parser/wheelhouse/*.whl